ansible_lint:
  extra_vars:
    targets: targets
  skip_list:
    - sanity[cannot-ignore]  # wokeignore:rule=sanity
github_actions:
  weekly_ci:
    schedule:
      - cron: "0 5 * * 6"
  codeql:
    schedule:
      - cron: "48 9 * * 6"
tmt_hardware:
  network:
    - type: eth
    - type: eth
runtime_collection_requirements:
  - name: ansible.posix
test_collection_requirements: []
