github_actions:
  weekly_ci:
    schedule:
      - cron: "0 22 * * 6"
  codeql:
    schedule:
      - cron: "8 10 * * 3"
runtime_collection_requirements:
  - name: ansible.posix
  - name: fedora.linux_system_roles
test_collection_requirements: []
