github_actions:
  weekly_ci:
    schedule:
      - cron: "0 8 * * 6"
ansible_lint:
  extra_kinds:
    - tasks: "**/tasks/*.yml"
runtime_collection_requirements:
  - name: ansible.posix
  - name: fedora.linux_system_roles
test_collection_requirements: []
