github_actions:
  weekly_ci:
    schedule:
      - cron: "0 12 * * 6"
  codeql:
    schedule:
      - cron: "48 10 * * 2"
runtime_collection_requirements:
  - name: ansible.posix
  - name: fedora.linux_system_roles
test_collection_requirements: []
