github_actions:
  weekly_ci:
    schedule:
      - cron: "0 11 * * 6"
  codeql:
    schedule:
      - cron: "24 13 * * 2"
runtime_collection_requirements: []
test_collection_requirements:
  - name: fedora.linux_system_roles
