github_actions:
  weekly_ci:
    schedule:
      - cron: "0 16 * * 6"
ansible_lint:
  exclude_paths:
    - tests/files/
  skip_list:
    - sanity[cannot-ignore]  # wokeignore:rule=sanity
runtime_collection_requirements:
  - name: ansible.posix
  - name: containers.podman
  - name: fedora.linux_system_roles
test_collection_requirements:
  - name: containers.podman
  - name: fedora.linux_system_roles
