github_actions:
  weekly_ci:
    schedule:
      - cron: "0 18 * * 6"
ansible_lint:
  mock_roles:
    - linux-system-roles.certificate
runtime_collection_requirements:
  - name: ansible.posix
  - name: fedora.linux_system_roles
test_collection_requirements: []
