github_actions:
  weekly_ci:
    schedule:
      - cron: "0 19 * * 6"
runtime_collection_requirements:
  - name: ansible.posix
  - name: community.general
    version: "{{ community_general_version }}"
test_collection_requirements:
  - name: fedora.linux_system_roles
