github_actions:
  weekly_ci:
    schedule:
      - cron: "0 22 * * 6"
  codeql:
    schedule:
      - cron: "8 10 * * 3"
role_specific_contributing: include_files/storage_contributing.md
runtime_collection_requirements:
  - name: ansible.posix
test_collection_requirements:
  - name: fedora.linux_system_roles
