github_actions:
  weekly_ci:
    schedule:
      - cron: "0 23 * * 6"
  codeql:
    schedule:
      - cron: "4 3 * * 2"
runtime_collection_requirements:
  - name: ansible.posix
test_collection_requirements: []
