github_actions:
  weekly_ci:
    schedule:
      - cron: "0 4 * * 0"
  codeql:
    schedule:
      - cron: "8 10 * * 3"
ansible_lint:
  skip_list:
    - sanity[cannot-ignore]  # wokeignore:rule=sanity
runtime_collection_requirements:
  - name: ansible.posix
  - name: fedora.linux_system_roles
test_collection_requirements: []
