present_files:
  - .github/dependabot.yml
  - .github/pull_request_template.md
  - .commitlintrc.js
  - .fmf/version
  - .markdownlint.yaml
  - .pandoc_template.html5
  - .ostree/get_ostree_data.sh
  - .ostree/README.md
  - README-ostree.md
present_templates:
  - .ansible-lint
  - .codespellrc
  - .yamllint.yml
  - contributing.md
  - .github/workflows/ansible-lint.yml
  - .github/workflows/ansible-managed-var-comment.yml
  - .github/workflows/ansible-test.yml
  - .github/workflows/build_docs.yml
  - .github/workflows/changelog_to_tag.yml
  - .github/workflows/codespell.yml
  - .github/workflows/markdownlint.yml
  - .github/workflows/pr-title-lint.yml
  - .github/workflows/qemu-kvm-integration-tests.yml
  - .github/workflows/test_converting_readme.yml
  - .github/workflows/tft.yml
  - .github/workflows/tft_citest_bad.yml
  - .github/workflows/weekly_ci.yml
  - .github/workflows/woke.yml
  - README-ansible.md
  - plans/README-plans.md
  - plans/test_playbooks_parallel.fmf
  - tests/vars/rh_distros_vars.yml
absent_files:
  - .github/workflows/ansible-plugin-scan.yml
  - .github/workflows/commitlint.yml
  - .github/workflows/tox.yml
  - README-devel.md
  - README-testing.md
  - .github/actions/custom-woke-action/LICENSE
  - .github/actions/custom-woke-action/README.md
  - .github/actions/custom-woke-action/action.yml
  - .github/actions/custom-woke-action/entrypoint.sh
  - .github/actions/custom-woke-action/testdata/bad.txt
  - .github/actions/custom-woke-action
  - .github/actions
github_org: linux-system-roles
github_url_prefix: "git@github.com:"
default_ansible_lint:
  skip_list:
    - fqcn-builtins
    - var-naming[no-role-prefix]
  warn_list: []
  exclude_paths:
    - tests/roles/
    - .github/
    - .markdownlint.yaml
    - examples/roles/
  mock_roles:
    - linux-system-roles.{{ inventory_hostname }}
lsr_namespace: fedora
lsr_name: linux_system_roles
lsr_role_namespace: linux_system_roles  # for ansible-lint
gha_checkout_action: actions/checkout@v5
tox_lsr_url: "git+https://github.com/linux-system-roles/tox-lsr@3.14.0"
# These are the supported RHEL-alike distros - note that at the time of writing,
# OracleLinux has some problems with some roles, so we don't include it here
# Roles that do support OracleLinux can list it in lsr_rh_distros_extra
lsr_rh_distros: "{{ ['AlmaLinux', 'CentOS', 'RedHat', 'Rocky'] + lsr_rh_distros_extra | d([]) }}"
# the lower bound is an older version, but I don't want to restrict the ability of a user
# of a particular role to use an old version, rather than forcing them to use 11.x or later
# Some roles like rhc explicitly require 6.6.0 or later - I think this is a reasonable
# lower bound for all roles
# If a role needs a different version, the role can define its own community_general_version
# in the role's host_vars file
community_general_version: ">=6.6.0,<12.0.0"
