present_files:
  - .github/dependabot.yml
  - .github/pull_request_template.md
  - .commitlintrc.js
  - .markdownlint.yaml
  - .pandoc_template.html5
present_templates:
  - .ansible-lint
  - .yamllint.yml
  - contributing.md
  - .github/workflows/ansible-lint.yml
  - .github/workflows/ansible-managed-var-comment.yml
  - .github/workflows/ansible-plugin-scan.yml
  - .github/workflows/ansible-test.yml
  - .github/workflows/build_docs.yml
  - .github/workflows/changelog_to_tag.yml
  - .github/workflows/markdownlint.yml
  - .github/workflows/pr-title-lint.yml
  - .github/workflows/test_converting_readme.yml
  - .github/workflows/weekly_ci.yml
  - .github/workflows/woke.yml
  - README-ansible.md

absent_files:
  - .github/workflows/commitlint.yml
  - .github/workflows/tox.yml
  - README-devel.md
  - README-testing.md
  - .github/actions/custom-woke-action/LICENSE
  - .github/actions/custom-woke-action/README.md
  - .github/actions/custom-woke-action/action.yml
  - .github/actions/custom-woke-action/entrypoint.sh
  - .github/actions/custom-woke-action/testdata/bad.txt
  - .github/actions/custom-woke-action
  - .github/actions

github_org: linux-system-roles
github_url_prefix: "https://github.com/"
default_ansible_lint:
  skip_list:
    - fqcn-builtins
    - var-naming[no-role-prefix]
  warn_list: []
  exclude_paths:
    - tests/roles/
    - .github/
    - .markdownlint.yaml
    - examples/roles/
  mock_roles:
    - linux-system-roles.{{ inventory_hostname }}
lsr_namespace: fedora
lsr_name: linux_system_roles
lsr_role_namespace: linux_system_roles  # for ansible-lint
gha_checkout_action: actions/checkout@v3
tox_lsr_url: "git+https://github.com/linux-system-roles/tox-lsr@3.0.0"
